# Generated by Django 4.2.4 on 2023-09-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='assigned_to_group',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assignby',
            new_name='assigned_to_user',
        ),
    ]
